package com.ltmonitor.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.rpc.holders.StringHolder;
import javax.xml.ws.Holder;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IJTXXservice service = new IJTXXservice();
 * IJTXX portType = service.getIJTXXPort();
 * portType.serviceAdapter(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "IJTXXservice", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://171.8.1.5:42080/Apache_Jtxx/wsdl/IJTXX")
public class IJTXXservice extends Service {

	private final static URL IJTXXSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ltmonitor.test.IJTXXservice.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ltmonitor.test.IJTXXservice.class.getResource(".");
			url = new URL(baseUrl,
					"http://171.8.1.5:42080/Apache_Jtxx/wsdl/IJTXX");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://171.8.1.5:42080/Apache_Jtxx/wsdl/IJTXX', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IJTXXSERVICE_WSDL_LOCATION = url;
	}

	public IJTXXservice(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IJTXXservice() {
		super(IJTXXSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"IJTXXservice"));
	}

	/**
	 * 
	 * @return returns IJTXX
	 */
	@WebEndpoint(name = "IJTXXPort")
	public IJTXX getIJTXXPort() {
		return super.getPort(new QName("http://tempuri.org/", "IJTXXPort"),
				IJTXX.class);
	}
	
	public static void main(String[] args) {

		IJTXXservice s = new IJTXXservice();
		IJTXX tx = s.getIJTXXPort();
		String param = "carno=E55565,carcolor=»ÆÉ«,userid=10001,carno=³µÅÆºÅ,carcolor=ÑÕÉ«,userid=10001";
		//StringHolder p = new StringHolder(param);
		Holder<String> h = new Holder<String>(param);
		Holder<Integer> t = new Holder<Integer>(0);
		tx.serviceAdapter("1x1001", h, t);
	}

}
