package com.ltmonitor.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IJTXX", targetNamespace = "http://tempuri.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IJTXX {

	/**
	 * 
	 * @param flag
	 * @param param
	 * @param adapterKey
	 * @return returns int
	 */
	@WebMethod(operationName = "ServiceAdapter")
	@WebResult(partName = "return")
	public int serviceAdapter(
			@WebParam(name = "AdapterKey", partName = "AdapterKey") String adapterKey,
			@WebParam(name = "Param", mode = WebParam.Mode.INOUT, partName = "Param") Holder<String> param,
			@WebParam(name = "flag", mode = WebParam.Mode.INOUT, partName = "flag") Holder<Integer> flag);

}
